Vojkan94/BIT-BOOK

src/view/App.css, src/view/App.js, src/view/components/Footer.js, src/view/components/Header.js, src/view/pages/Main/Main.js
Header should contain navigation items Feed (main page), People (users), Profile (my profile)
Main content should be feed and if there are not any feed items yet it should display “Nothing in feed” message
Footer should contain my team name and year
closes #4
=> [book-0] App navigation

src/models/Post.js, src/services/postService.js, src/shared/constants.js, src/view/App.js, src/view/components/common/Footer.js, src/view/components/feed/PostCountComment.js, src/view/components/feed/PostImage.js, src/view/components/feed/PostItem.js, src/view/components/feed/PostList.js, src/view/components/feed/PostText.js, src/view/components/feed/PostVideo.js
=> Posts Feed - Fetch

package.json, src/index.js, src/shared/ButtonAnimation.js, src/view/App.js, src/view/components/feed/ButtonFeed/NewImageModal.js, src/view/components/feed/ButtonFeed/NewPostButton.css, src/view/components/feed/ButtonFeed/NewPostButton.js, src/view/components/feed/ButtonFeed/NewTextModal.js, src/view/components/feed/ButtonFeed/NewVideoModal.js, src/view/components/main/Main.js, yarn.lock
As a user I should be able to create new post of different type (text, video and image posts)
- Add Font Awesome
-Add jQuery
closes #10
=> [book-2] - Create Post(s) - View

src/index.js, src/services/postService.js, src/view/components/feed/ButtonFeed/CollectImageInput.js, src/view/components/feed/ButtonFeed/CollectTextInput.js, src/view/components/feed/ButtonFeed/CollectVideoInput.js, src/view/components/feed/ButtonFeed/NewImageModal.js, src/view/components/feed/ButtonFeed/NewPostButton.js, src/view/components/feed/ButtonFeed/NewTextModal.js, src/view/components/feed/ButtonFeed/NewVideoModal.js
As I user when I create post I should be able to see it on the top of my feed
As a user when creating post I should be able to see if my input is invalid for that post type
closes #14
=> [book-2] - Create Post(s) - Send post

src/models/Comment.js, src/services/apiService.js, src/services/postService.js, src/view/App.css, src/view/components/common/Header.js, src/view/components/feed/PostItem.js, src/view/components/feed/PostVideo.js, src/view/components/main/Main.js, src/view/components/singlePost/SinglePost.js, src/view/components/singlePost/comment/CommentInput.js, src/view/components/singlePost/comment/CommentItem.js, src/view/components/singlePost/comment/CommentList.js
- As a user I should be able to open each post and see its content
- As a user beside post content I should be able only to see post comments below it (if there are any)
=> 13 view post

src/services/apiService.js, src/services/postService.js, src/view/components/singlePost/SinglePost.js, src/view/components/singlePost/comment/CommentInput.js, src/view/components/singlePost/comment/CommentItem.js, src/view/components/singlePost/comment/CommentList.js
- implement apiService with get and post methods
- chenge html for comments 
#13
=> 10 view post

src/services/validationService.js, src/view/components/feed/ButtonFeed/NewImageModal.js, src/view/components/feed/ButtonFeed/NewPostButton.js, src/view/components/feed/ButtonFeed/NewTextModal.js, src/view/components/feed/ButtonFeed/NewVideoModal.js, src/view/components/feed/PostList.js
- For video post only youtube links are valid input
- Links should be appropriately formatted to be “embedded”
- Input: https://www.youtube.com/watch?v=gAJkikwPtBs
- Output: https://www.youtube.com/embed/gAJkikwPtBs
- For image only image urls are valid input
closes #15
=> 14 create post

src/services/postService.js, src/view/components/singlePost/comment/CommentInput.js, src/view/components/singlePost/comment/CommentList.js
-     As a user when I preview post content, I should be able to type in a comment about that post and send it via send button
-     When comment input field is empty, send button should be disabled
-     As I user when I leave a comment, I should be able to see it below my post
=> add post comment

src/view/components/common/Header.js, src/view/components/main/Main.js, src/view/components/people/UserItem.js, src/view/components/people/UserList.js, src/view/components/people/UserSearch.js
=> 22-people-page-view

src/models/User.js, src/services/postService.js, src/services/userService.js, src/shared/dateFormat.js, src/view/components/people/UserItem.js, src/view/components/people/UserList.js
import fetch for all users and add user modal
=> Add fetch users, add user constructor

src/shared/dateFormat.js, src/view/components/people/UserItem.js, src/view/components/people/UserList.js, src/view/components/people/UserSearch.js
finished fetch for users and implement user Search
=> 23-people-page-fetch

src/services/userService.js, src/view/components/main/Main.js, src/view/components/myProfile/MyProfilePage.js, src/view/components/myProfile/UserProfile.js, src/view/components/people/UserList.js
As a user I should be able to open each user's page and see information same as my profile page (see Feature 5).
closes #28
=> 28 view people profile

src/services/apiService.js, src/services/postService.js, src/view/components/feed/PostDelete.js, src/view/components/feed/PostImage.js, src/view/components/feed/PostItem.js, src/view/components/feed/PostList.js, src/view/components/feed/PostText.js, src/view/components/feed/PostVideo.js, src/view/components/singlePost/SinglePost.js, src/view/components/singlePost/comment/CommentList.js
1. As a user I should be able to delete my post
=> Feature 9 - Deleting Posts and Comments

public/index.html, src/services/apiService.js, src/view/components/feed/PostFilter.js, src/view/components/feed/PostImage.js, src/view/components/feed/PostItem.js, src/view/components/feed/PostList.js, src/view/components/feed/PostText.js, src/view/components/feed/PostVideo.js, src/view/components/singlePost/SinglePost.js, src/view/components/singlePost/comment/CommentInput.js, src/view/components/singlePost/comment/CommentItem.js, src/view/components/singlePost/comment/CommentList.js
As a user I should be able to filter posts by post type (text, video and image) on the feed page
As a user when I select one of the following options, only posts of that type should be visible on the feed
=> Feature 10 - Filter Posts on Feed Page

src/view/components/feed/PostImage.js, src/view/components/feed/PostItem.js, src/view/components/feed/PostList.js, src/view/components/feed/PostText.js, src/view/components/feed/PostVideo.js, src/view/components/singlePost/SinglePost.js
=> Set localstorage userId

src/index.js, src/services/apiService.js, src/services/postService.js, src/services/userService.js, src/shared/ButtonAnimation.js, src/shared/history.js, src/view/components/feed/ButtonFeed/NewImageModal.js, src/view/components/feed/ButtonFeed/NewTextModal.js, src/view/components/feed/ButtonFeed/NewVideoModal.js, src/view/components/feed/PostImage.js, src/view/components/feed/PostItem.js, src/view/components/feed/PostList.js, src/view/components/feed/PostText.js, src/view/components/feed/PostVideo.js, src/view/components/myProfile/MyProfilePage.js, src/view/components/myProfile/UserProfile.js, src/view/components/people/UserItem.js, src/view/components/people/UserList.js, src/view/components/people/UserSearch.js, src/view/components/people/css/people.css, src/view/components/singlePost/SinglePost.js, src/view/components/singlePost/comment/CommentInput.js, src/view/components/singlePost/comment/CommentList.js
- Setting reload page after deleting post
- Setting reload comments
=> 39 refactoring code

src/services/validationService.js, src/view/App.css, src/view/components/common/Footer.js, src/view/components/common/Header.js, src/view/components/main/Main.js, src/view/components/welcome/WelcomeAbout.js, src/view/components/welcome/WelcomeList.js, src/view/components/welcome/WelcomeLogin.js, src/view/components/welcome/WelcomePage.js, src/view/components/welcome/WelcomeRegister.js
=> [book-11] Feature 11 - Login 

src/services/apiService.js, src/services/userService.js, src/services/validationService.js, src/view/components/feed/ButtonFeed/ModalFeed.js, src/view/components/feed/ButtonFeed/NewImageModal.js, src/view/components/feed/ButtonFeed/NewPostButton.js, src/view/components/feed/ButtonFeed/NewTextModal.js, src/view/components/feed/ButtonFeed/NewVideoModal.js, src/view/components/feed/PostList.js, src/view/components/myProfile/EditProfileButton.js, src/view/components/myProfile/EditProfileModal.js, src/view/components/myProfile/Modal.js, src/view/components/myProfile/MyProfileDesc.js, src/view/components/myProfile/MyProfilePage.js, src/view/components/myProfile/MyProfilePicAndName.js, src/view/components/singlePost/comment/CommentItem.js
- As a user I should be able to change my profile picture
- Image can be add by providing link to the image
- Image can be added by uploading image from the disk
=> 31 edit profile

src/services/apiService.js, src/services/userService.js, src/view/components/welcome/WelcomeRegister.js
- As a user, I should have an option to register
-  Clicking on the Register tab should display the registration form
=> Register system

src/services/validationService.js, src/view/components/common/Header.js, src/view/components/feed/ButtonFeed/NewImageModal.js, src/view/components/feed/ButtonFeed/NewTextModal.js, src/view/components/feed/ButtonFeed/NewVideoModal.js, src/view/components/feed/PostItem.js, src/view/components/main/Main.js, src/view/components/myProfile/EditProfileModal.js, src/view/components/people/UserList.js, src/view/components/singlePost/comment/CommentInput.js, src/view/components/welcome/WelcomeList.js, src/view/components/welcome/WelcomeLogin.js, src/view/components/welcome/WelcomeRegister.js
=> Feature 11 - Login

src/services/validationService.js, src/view/components/welcome/WelcomeRegister.js
=> 46 register

src/services/validationService.js, src/view/components/welcome/WelcomeRegister.js
implement register validation for all inputs
=> implement register validation

src/services/userService.js, src/services/validationService.js, src/view/App.css, src/view/components/feed/ButtonFeed/ModalFeed.js, src/view/components/feed/ButtonFeed/NewPostButton.js, src/view/components/feed/PostCountComment.js, src/view/components/feed/PostFilter.js, src/view/components/feed/PostImage.js, src/view/components/feed/PostItem.js, src/view/components/feed/PostText.js, src/view/components/feed/PostVideo.js, src/view/components/feed/css/PostText.css, src/view/components/main/Main.js, src/view/components/myProfile/EditProfileButton.js, src/view/components/myProfile/EditProfileModal.js, src/view/components/myProfile/Modal.js, src/view/components/myProfile/MyProfilePage.js, src/view/components/myProfile/UserProfile.js
=> 39-refactoring-code

src/view/components/welcome/WelcomeRegister.js
=> validation on enter

src/view/components/feed/ButtonFeed/NewImageModal.js, src/view/components/feed/ButtonFeed/NewPostButton.css, src/view/components/feed/ButtonFeed/NewTextModal.js, src/view/components/feed/ButtonFeed/NewVideoModal.js, src/view/components/myProfile/EditProfileButton.js, src/view/components/myProfile/css/MyProfile.css, src/view/components/people/css/people.css
- Edit modal input style
- Edit style button for edit page
- Edit  style date span on people page
=> 36 edit style

src/view/components/feed/PostCountComment.js
=> Edit comment icon style
